  <?php
    //begin login session, initialise register variables
    session_start();
    $_SESSION["userTaken"]="";
    //connect to MySQL database, details from external server
    include "connect.php";
    //fetch entered information
    $fName=$_POST["fName"];
    $sName=$_POST["sName"];
    $eAddr=$_POST["eAddr"];
    $uName=$_POST["uName"];
    $pWord=password_hash($_POST["pWord"],PASSWORD_DEFAULT);
    //query the database to check the username entered is not already in use
    $query="SELECT * FROM members WHERE username='$uName'";
    $result=$conn->query($query);
    if($result->num_rows==0) {
        //if unique, proceed with registration
        $query="INSERT INTO members (username,password,forename,surname,email) VALUES ('$uName','$pWord','$fName','$sName','$eAddr')";
        $conn->query($query);
        //fetch user id generated by MySQL server
        $query="SELECT * FROM members WHERE username='$uName'";
        $result=$conn->query($query);
        $row=$result->fetch_assoc();
        $id=$row["id"];
        //inform session of id, and redirect to welcome page
        $_SESSION["userId"]=$id;
        //and we need to create profile
        $date=date('Y/m/d');
        $query="INSERT INTO profile (id,birthday) VALUES ($id,$date)";
        $conn->query($query);
        header("Location: /thinkly/?page=welcome");
        die();
    }
    else {
        //otherwise, inform session of error and return to login
        $_SESSION["userTaken"]=True;
        header("Location: /thinkly/?page=login");
        die();
    }
?>
